pm_user_role_edit:
    path:     /role/{id}/edit/
    defaults: { _controller: ProjectManagerUserBundle:Role:edit }
    methods:  [GET, POST]

pm_user_role_add:
    path:     /role/new
    defaults: { _controller: ProjectManagerUserBundle:Role:edit }
    methods:  [GET, POST]

pm_user_role_list:
    path:     /role/
    defaults: { _controller: ProjectManagerUserBundle:Role:index }
    methods:  [GET]

pm_user_role_delete:
    path:     /role/{id}
    defaults: { _controller: ProjectManagerUserBundle:Role:delete }
    methods:  [DELETE]
