pm_user_team_list:
    path:     /team/
    defaults: { _controller: ProjectManagerUserBundle:Team:index }
    methods:  [GET]

pm_user_team_add:
    path:     /team/new/
    defaults: { _controller: ProjectManagerUserBundle:Team:new }
    methods:  [GET]

pm_user_team_create:
    path:     /team/
    defaults: { _controller: ProjectManagerUserBundle:Team:create }
    methods:  [POST]

pm_user_team_edit:
    path:     /team/{id}/edit/
    defaults: { _controller: ProjectManagerUserBundle:Team:edit }
    methods:  [GET]

pm_user_team_update:
    path:     /team/{id}/
    defaults: { _controller: ProjectManagerUserBundle:Team:update }
    methods:  [PUT]

pm_user_team_delete:
    path:     /team/{id}/
    defaults: { _controller: ProjectManagerUserBundle:Team:delete }
    methods:  [DELETE]

pm_user_teammember_list:
    path:     /teammember/{teamId}/list/
    defaults: { _controller: ProjectManagerUserBundle:TeamMember:list }
    methods:  [GET]

pm_user_teammember_list_not_in_team:
    path:     /teammember/{teamId}/notInlist/
    defaults: { _controller: ProjectManagerUserBundle:TeamMember:listNotInTeam }
    methods:  [GET]

pm_user_teammember_team_member_add_members:
    path:     /teammember/{teamId}/add_members/
    defaults: { _controller: ProjectManagerUserBundle:TeamMember:addMembersToTeam }
    methods:  [GET,POST]

pm_user_teammember_delete_member:
    path:     /teammember/{teamId}/{id}/
    defaults: { _controller: ProjectManagerUserBundle:TeamMember:deleteMember }
    methods:  [DELETE]

pm_user_teammember_update_roles:
    path:     /teammember/{teamId}/{userId}/update_roles/
    defaults: { _controller: ProjectManagerUserBundle:TeamMember:updateRolesForUserInTeam }
    methods:  [PUT]
