pm_user_user_edit:
    path:     /user/{id}/edit/
    defaults: { _controller: ProjectManagerUserBundle:User:update }
    requirements:
        _method:  GET|POST

pm_user_user_add:
    path:     /user/new
    defaults: { _controller: ProjectManagerUserBundle:User:update }
    requirements:
        _method:  GET|POST

pm_user_user_list:
    path:     /user/
    defaults: { _controller: ProjectManagerUserBundle:User:index }
    requirements:
        _method:  GET

pm_user_user_delete:
    path:     /user/{id}
    defaults: { _controller: ProjectManagerUserBundle:User:delete }
    requirements:
        _method:  DELETE
