pm_user_user_edit:
    path:     /user/{id}/edit/
    defaults: { _controller: ProjectManagerUserBundle:User:update }
    methods:  [GET,POST]

pm_user_user_add:
    path:     /user/new
    defaults: { _controller: ProjectManagerUserBundle:User:update }
    methods:  [GET,POST]

pm_user_user_list:
    path:     /user/
    defaults: { _controller: ProjectManagerUserBundle:User:index }
    methods:  [GET]

pm_user_user_delete:
    path:     /user/{id}
    defaults: { _controller: ProjectManagerUserBundle:User:delete }
    methods:  [DELETE]
