language: php
php: [ "5.5" ]
script: bin/behat

before_script:
    - sudo apt-get update -qq
    - composer self-update
    - composer install
    - echo "- drop database"
    - php app/console doctrine:database:drop --force -q || true
    - echo "- create database"
    - php app/console doctrine:database:create -q
    - echo "- create SQL schema"
    - php app/console doctrine:schema:create -q
    - cp behat.yml.dist behat.yml

    - sudo apt-get install apache2 libapache2-mod-fastcgi
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f .travis.vhost.conf /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart

    # Firefox
    - sudo apt-get install -y --force-yes firefox
    
    # XVFB
    - "Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>/dev/null &"
    - "export DISPLAY=:0"

    # Selenium server
    - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
    - "java -jar selenium-server-standalone-2.45.0.jar > /dev/null 2>/dev/null &"

