language: php
php: [ "5.4" ]
script: bin/behat

before_script:
    - sudo apt-get update -qq
    - composer self-update
    - composer install
    - echo "- drop database"
    - php app/console doctrine:database:drop --force -q || true
    - echo "- create database"
    - php app/console doctrine:database:create -q
    - echo "- create SQL schema"
    - php app/console doctrine:schema:create -q
    - cp behat.yml.dist behat.yml

    # Firefox
    - sudo apt-get install -y --force-yes firefox
    
    # XVFB
    - "Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>/dev/null &"
    - "export DISPLAY=:0"
    
    # Window manager
    - "sudo apt-get install fluxbox -y --force-yes"
    - "fluxbox &"

    # Selenium server
    - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
    - "java -jar selenium-server-standalone-2.45.0.jar > /dev/null 2>/dev/null &"

