project_manager_people_homepage:
    path:     /hello/
    defaults: { _controller: ProjectManagerPeopleBundle:Default:index }

project_manager_people_update_person:
    path:     /person/update/{id}
    defaults: { _controller: ProjectManagerPeopleBundle:Person:update }

project_manager_people_new_person:
    path:     /person/new
    defaults: { _controller: ProjectManagerPeopleBundle:Person:update }

project_manager_people_list_person:
    path:     /person/list
    defaults: { _controller: ProjectManagerPeopleBundle:Person:index }

project_manager_people_delete_person:
    path:     /person/delete/{id}
    defaults: { _controller: ProjectManagerPeopleBundle:Person:delete }