project_manager_people_homepage:
    path:     /hello/
    defaults: { _controller: ProjectManagerPeopleBundle:Default:index }

project_manager_people_new_person:
    path:     /people/new
    defaults: { _controller: ProjectManagerPeopleBundle:Person:new }

project_manager_people_list_person:
    path:     /people/list
    defaults: { _controller: ProjectManagerPeopleBundle:Person:index }

project_manager_people_delete_person:
    path:     /people/delete/{id}
    defaults: { _controller: ProjectManagerPeopleBundle:Person:delete }