pm_user:
    resource: "@ProjectManagerUserBundle/Resources/config/routing/user.yml"

pm_team:
    resource: "@ProjectManagerUserBundle/Controller/TeamController.php"
    type:     annotation

pm_teammember:
    resource: "@ProjectManagerUserBundle/Controller/TeamMemberController.php"
    type:     annotation
