pm_user_update_person:
    path:     /person/{id}/update/
    defaults: { _controller: ProjectManagerUserBundle:User:update }

pm_user_new_person:
    path:     /person/new
    defaults: { _controller: ProjectManagerUserBundle:User:update }

pm_user_list_person:
    path:     /person/list
    defaults: { _controller: ProjectManagerUserBundle:User:index }

pm_user_delete_person:
    path:     /person/{id}/delete/
    defaults: { _controller: ProjectManagerUserBundle:User:delete }

pm_team:
    resource: "@ProjectManagerUserBundle/Controller/TeamController.php"
    type:     annotation

pm_teammember:
    resource: "@ProjectManagerUserBundle/Controller/TeamMemberController.php"
    type:     annotation