pm_user_update_person:
    path:     /user/{id}/update/
    defaults: { _controller: ProjectManagerUserBundle:User:update }

pm_user_new_person:
    path:     /user/new
    defaults: { _controller: ProjectManagerUserBundle:User:update }

pm_user_list_person:
    path:     /user/
    defaults: { _controller: ProjectManagerUserBundle:User:index }

pm_user_delete_person:
    path:     /user/{id}/delete/
    defaults: { _controller: ProjectManagerUserBundle:User:delete }

pm_team:
    resource: "@ProjectManagerUserBundle/Controller/TeamController.php"
    type:     annotation

pm_teammember:
    resource: "@ProjectManagerUserBundle/Controller/TeamMemberController.php"
    type:     annotation