pm_user:
    resource: "@ProjectManagerUserBundle/Resources/config/routing/user.yml"

pm_team:
    resource: "@ProjectManagerUserBundle/Resources/config/routing/team.yml"

pm_role:
    resource: "@ProjectManagerUserBundle/Resources/config/routing/role.yml"

