pm_project_project_list:
    path:     /project/
    defaults: { _controller: ProjectManagerProjectBundle:Project:index }
    methods:  [GET]

pm_project_project_add:
    path:     /project/new
    defaults: { _controller: ProjectManagerProjectBundle:Project:new }
    methods:  [GET, POST]

pm_project_project_delete:
    path:     /project/{id}
    defaults: { _controller: ProjectManagerProjectBundle:Project:delete }
    methods:  [DELETE]

pm_project_project_edit:
    path:     /project/{id}
    defaults: { _controller: ProjectManagerProjectBundle:Project:edit }
    methods:  [GET,POST]
