pm_project_task_list:
    path:     /project/{projectId}/tasks
    defaults: { _controller: ProjectManagerProjectBundle:Task:index }
    requirements:
        _method:  GET

pm_project_task_delete:
    path:     /project/{projectId}/tasks/{id}
    defaults: { _controller: ProjectManagerProjectBundle:Task:delete }
    requirements:
        _method:  DELETE

pm_project_task_add:
    path:     /project/{projectId}/tasks/new
    defaults: { _controller: ProjectManagerProjectBundle:Task:new }
    requirements:
        _method:  GET|POST
